I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/opening.rpy", line 51, in script call
    call others
  File "game/buildings.rpy", line 10, in script call
    call eleven
  File "game/opening.rpy", line 51, in script call
    call others
  File "game/buildings.rpy", line 10, in script call
    call eleven
ScriptError: could not find label 'eleven'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/opening.rpy", line 51, in script call
    call others
  File "game/buildings.rpy", line 10, in script call
    call eleven
  File "D:\Short-Novel\renpy_engine\renpy\ast.py", line 1436, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/opening.rpy", line 51, in script call
    call others
  File "game/buildings.rpy", line 10, in script call
    call eleven
  File "D:\Short-Novel\renpy_engine\renpy\script.py", line 894, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'eleven'.

Windows-8-6.2.9200
Ren'Py 7.3.4.596
csg 1.0
Fri Nov 01 21:53:37 2019
